require("conf")

require("plugins.ui")
require("plugins.lsp")
require("plugins.mason")
require("plugins.snacks")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.debug")
require("plugins.markdown")
require("plugins.img-clip")
require("plugins.opencode")
